### ISSUE TITLE
Dataclasses: `for_` or use subclassing?

### ISSUE THREAD

**Issue by pauleveritt** [mmerickel/wired#20]
*This is a design question for Michael.*

As [shown in the example](https://wired-paul.readthedocs.io/en/dataclasses/dc/overrides/index.html), you register a dataclass with a `for_` argument in the decorator:

```python
@factory(for_=Greeter, context=FrenchCustomer)
@dataclass
class FrenchGreeter:
    settings: Settings
    name: str = 'Henri'
```

Behind the scenes, the value of `for_` becomes the second argument to `registry.register_factory`. Later, specialty decorators such as `@view` would allow eliding that and, behind the scenes, would supply `for_=View`. Or in the case above, `@greeter` would supply `for_=Greeter`.

Andrey (from PyCharm) argued that `FrenchGreeter` is a kind of `Greeter` and I should be doing `class FrenchGreeter(Greeter)`. The "system" should then be able to figure out via inheritance the match.

I'm not sure `wired` can do that. I'm also not sure it should. Open to suggestions.

**Comment by mmerickel** [comment]
> Andrey (from PyCharm) argued that FrenchGreeter is a kind of Greeter and I should be doing class FrenchGreeter(Greeter). The "system" should then be able to figure out via inheritance the match.

wired cannot currently do that for classes because z.i does not support it. I wish it would but it does not right now. z.i basically does not support classes at all and I hacked some basic support on for doing direct type-based lookup but inheritance is a whole thing I haven't tried to make work. It will work if you do `IFrenchGreeter(IGreeter)` with interfaces. Then when you query an IGreeter it will consider the IFrenchGreeter impl a match.

**Comment by pauleveritt** [comment]
IMO though I might like interfaces, it would be a negative point emphasizing it. I'll close this ticket and stick with `for_`. The specialty decorators will make it less noisy either way.

**Comment by mmerickel** [comment]
Note my updated code example just for posterity.
